

services:
  react-frontend:
    build:
      context: ./react_vite
      dockerfile: Dockerfile
    container_name: react_frontend
    expose:
      - "80"
    restart: always
    networks:
      - frontend

networks:
  frontend:
    external: true